package com.variety.shop.indi.collection.bean;/*
 * WmsMtSkuInfoModel_Field.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */

import java.math.BigDecimal;

/**
 * Model [wms_mt_sku_info]
 * <p>
 * This class was generated by code generator, please don't modify it.
 * 
 * @version 0.0.1 
 */
public abstract class WmsMtSkuInfoModel_Field extends BaseModel<Long> {
    /**
     * 渠道ID
     */
    protected String channelId;

    /**
     * SKU
     */
    protected String sku;

    /**
     * 原产地
     */
    protected String origin;

    /**
     * 成分
     */
    protected String ingredients;

    /**
     * 规格
     */
    protected String specification;

    /**
     * 原产地产品名
     */
    protected String originProductName;

    /**
     * 长（mm）
     */
    protected BigDecimal length;

    /**
     * 宽（mm）
     */
    protected BigDecimal width;

    /**
     * 高（mm）
     */
    protected BigDecimal height;

    /**
     * 实际长（mm）
     */
    protected BigDecimal actualLength;

    /**
     * 实际宽（mm）
     */
    protected BigDecimal actualWidth;

    /**
     * 实际高（mm）
     */
    protected BigDecimal actualHeight;

    /**
     * 是否已测量
     */
    protected Boolean measured;

    /**
     * 净重（g）
     */
    protected BigDecimal netWeight;

    /**
     * 毛重（g）
     */
    protected BigDecimal grossWeight;

    /**
     * 实际净重（g）
     */
    protected BigDecimal actualNetWeight;

    /**
     * 实际毛重（g）
     */
    protected BigDecimal actualGrossWeight;

    /**
     * 是否已称重
     */
    protected Boolean weighed;

    /**
     * 价格
     */
    protected BigDecimal price;

    /**
     * 价格单位
     */
    protected String priceUnit;

    /**
     * 原产地价格
     */
    protected BigDecimal originPrice;

    /**
     * 原产地价格单位
     */
    protected String originPriceUnit;

    /**
     * 海关编码
     */
    protected String hsCode;

    /**
     * 申报名称
     */
    protected String declareName;

    /**
     * 申报单位
     */
    protected String declareUnit;

    /**
     * 原产地申报名称
     */
    protected String originDeclareName;

    /**
     * 原产地申报单位
     */
    protected String originDeclareUnit;

    /**
     * 是否有效（1:有效；0：无效）
     */
    protected Boolean active;

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    public String getOrigin() {
        return origin;
    }

    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    public String getIngredients() {
        return ingredients;
    }

    public void setIngredients(String ingredients) {
        this.ingredients = ingredients == null ? null : ingredients.trim();
    }

    public String getSpecification() {
        return specification;
    }

    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    public String getOriginProductName() {
        return originProductName;
    }

    public void setOriginProductName(String originProductName) {
        this.originProductName = originProductName == null ? null : originProductName.trim();
    }

    public BigDecimal getLength() {
        return length;
    }

    public void setLength(BigDecimal length) {
        this.length = length;
    }

    public BigDecimal getWidth() {
        return width;
    }

    public void setWidth(BigDecimal width) {
        this.width = width;
    }

    public BigDecimal getHeight() {
        return height;
    }

    public void setHeight(BigDecimal height) {
        this.height = height;
    }

    public BigDecimal getActualLength() {
        return actualLength;
    }

    public void setActualLength(BigDecimal actualLength) {
        this.actualLength = actualLength;
    }

    public BigDecimal getActualWidth() {
        return actualWidth;
    }

    public void setActualWidth(BigDecimal actualWidth) {
        this.actualWidth = actualWidth;
    }

    public BigDecimal getActualHeight() {
        return actualHeight;
    }

    public void setActualHeight(BigDecimal actualHeight) {
        this.actualHeight = actualHeight;
    }

    public Boolean getMeasured() {
        return measured;
    }

    public void setMeasured(Boolean measured) {
        this.measured = measured;
    }

    public BigDecimal getNetWeight() {
        return netWeight;
    }

    public void setNetWeight(BigDecimal netWeight) {
        this.netWeight = netWeight;
    }

    public BigDecimal getGrossWeight() {
        return grossWeight;
    }

    public void setGrossWeight(BigDecimal grossWeight) {
        this.grossWeight = grossWeight;
    }

    public BigDecimal getActualNetWeight() {
        return actualNetWeight;
    }

    public void setActualNetWeight(BigDecimal actualNetWeight) {
        this.actualNetWeight = actualNetWeight;
    }

    public BigDecimal getActualGrossWeight() {
        return actualGrossWeight;
    }

    public void setActualGrossWeight(BigDecimal actualGrossWeight) {
        this.actualGrossWeight = actualGrossWeight;
    }

    public Boolean getWeighed() {
        return weighed;
    }

    public void setWeighed(Boolean weighed) {
        this.weighed = weighed;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getPriceUnit() {
        return priceUnit;
    }

    public void setPriceUnit(String priceUnit) {
        this.priceUnit = priceUnit == null ? null : priceUnit.trim();
    }

    public BigDecimal getOriginPrice() {
        return originPrice;
    }

    public void setOriginPrice(BigDecimal originPrice) {
        this.originPrice = originPrice;
    }

    public String getOriginPriceUnit() {
        return originPriceUnit;
    }

    public void setOriginPriceUnit(String originPriceUnit) {
        this.originPriceUnit = originPriceUnit == null ? null : originPriceUnit.trim();
    }

    public String getHsCode() {
        return hsCode;
    }

    public void setHsCode(String hsCode) {
        this.hsCode = hsCode == null ? null : hsCode.trim();
    }

    public String getDeclareName() {
        return declareName;
    }

    public void setDeclareName(String declareName) {
        this.declareName = declareName == null ? null : declareName.trim();
    }

    public String getDeclareUnit() {
        return declareUnit;
    }

    public void setDeclareUnit(String declareUnit) {
        this.declareUnit = declareUnit == null ? null : declareUnit.trim();
    }

    public String getOriginDeclareName() {
        return originDeclareName;
    }

    public void setOriginDeclareName(String originDeclareName) {
        this.originDeclareName = originDeclareName == null ? null : originDeclareName.trim();
    }

    public String getOriginDeclareUnit() {
        return originDeclareUnit;
    }

    public void setOriginDeclareUnit(String originDeclareUnit) {
        this.originDeclareUnit = originDeclareUnit == null ? null : originDeclareUnit.trim();
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }
}